//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoidDaysConsoleClient.VoidDaysLoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="VoidDaysLoginService.IVoidDaysLoginService")]
    public interface IVoidDaysLoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/CreateUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/CreateUserResponse")]
        void CreateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/CreateUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/LoginUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/LoginUserResponse")]
        string LoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/LoginUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidDaysLoginService/LoginUserResponse")]
        System.Threading.Tasks.Task<string> LoginUserAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoidDaysLoginServiceChannel : VoidDaysConsoleClient.VoidDaysLoginService.IVoidDaysLoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoidDaysLoginServiceClient : System.ServiceModel.ClientBase<VoidDaysConsoleClient.VoidDaysLoginService.IVoidDaysLoginService>, VoidDaysConsoleClient.VoidDaysLoginService.IVoidDaysLoginService {
        
        public VoidDaysLoginServiceClient() {
        }
        
        public VoidDaysLoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoidDaysLoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoidDaysLoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoidDaysLoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string username, string password) {
            base.Channel.CreateUser(username, password);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string username, string password) {
            return base.Channel.CreateUserAsync(username, password);
        }
        
        public string LoginUser(string username, string password) {
            return base.Channel.LoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginUserAsync(string username, string password) {
            return base.Channel.LoginUserAsync(username, password);
        }
    }
}
